Repository pool-party/pull-party-bot, pull requests merged in 2020-07, with the labels that each got.

#1 :tada: init gradle
  .editorconfig
  .gitignore
  README.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/kotlin/Main.kt
Labels: enhancement

#2 :bug: readme several bugs
  README.md
Labels: bug

#5 :bug: fix args order
  src/main/kotlin/Main.kt
Labels: bug, invalid

#22 :construction_worker: ci improvements
  .github/workflows/ktlint.yml
  .travis.yml
  README.md
  src/test/kotlin/com/github/pool_party/pull_party_bot/MockTest.kt
Labels: enhancement

#25 :card_file_box: database integration
  build.gradle
  src/main/kotlin/com/github/pool_party/pull_party_bot/Main.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommands.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Models.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
  src/main/resources/META-INF/MANIFEST.MF
Labels: enhancement

#27 :card_file_box: database daos
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Entities.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Models.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
Labels: enhancement

#32 :art: input handling improvement
  src/main/kotlin/com/github/pool_party/pull_party_bot/Main.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Entities.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Models.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
Labels: enhancement

#33 :sparkles: message party pulling
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
Labels: enhancement

#38 :sparkles: default admins group
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
Labels: enhancement

#39 :sparkles: add args validation
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
Labels: enhancement
