Repository pool-party/pull-party-bot, pull requests merged in 2020-12, with the labels that each got.

#94 :recycle: finally super refactoring
  src/main/kotlin/com/github/pool_party/pull_party_bot/Configuration.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/Main.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Command.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Handlers.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Utils.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/ChangePartyCommands.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/DeleteCommands.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/InformationCommands.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/PullPartyCommands.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/RudeCommand.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/messages/ChangePartyMessages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/messages/DeleteMessages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/messages/InformationMessages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/messages/PullPartyMessages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/messages/RudeMessage.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/dao/ChatDao.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/dao/PartyDao.kt
Labels: enhancement

#97 :sparkles: tests
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/kotlin/com/github/pool_party/pull_party_bot/Configuration.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/PullPartyCommands.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/AbstractCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/ClearCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/DeleteCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/ListCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/PullPartyCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/RudeCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/StartCommandTest.kt
Labels: dependencies, enhancement

#100 :white_check_mark: test
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/ChangePartyCommands.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/DeleteCommands.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/InformationCommands.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/RemoveSuggestionCallback.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/RudeCommand.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/messages/ChangePartyMessages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/messages/DeleteMessages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/messages/InformationMessages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/messages/RudeMessage.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/dao/PartyDao.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/AbstractChangeCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/CreateCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/ListCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/PullPartyCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/RudeCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/StartCommandTest.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/database/dao/ChatInMemoryDao.kt
  src/test/kotlin/com/github/pool_party/pull_party_bot/database/dao/PartyInMemoryDao.kt
Labels: enhancement

#101 :bookmark: changelog update
  CHANGELOG.md
  Procfile
  README.md
  build.gradle.kts
Labels: documentation
