Repository pool-party/pull-party-bot, pull requests merged in 2020-09, with the labels that each got.

#47 :bug: api improvement
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/database/Transactions.kt
Labels: bug, enhancement

#48 :recycle: code refactoring
  build.gradle
  src/main/kotlin/com/github/pool_party/pull_party_bot/Main.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Utils.kt
Labels: enhancement

#51 Bugfix/prefix
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
Labels: bug

#52 :art: punctuation marks handling
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
Labels: enhancement

#53 :memo: feature/extend help
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
Labels: documentation, enhancement

#55 :memo: update readme, sync with help
  README.md
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/Messages.kt
Labels: documentation, enhancement

#57 :pencil: adding changelog
  CHANGELOG.md
Labels: documentation

#59 :bug: fix media caption ignorance
  src/main/kotlin/com/github/pool_party/pull_party_bot/commands/PingCommandHandlers.kt
Labels: bug
